apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "kubedemo-worker.fullname" . }}"
  labels: 
    {{- include "kubedemo-worker.labels" . | nindent 4 }}

stringData:
  rabbitmqPassword: "{{ .Values.appConfig.rabbitmqPassword }}"
