name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push WebApp
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
      uses: docker/build-push-action@v2.3.0
      with:
        context: src/WebApp
        # List of tags
        tags: hallgeirl/kubedemo-web:1.0
        # Push is a shorthand for --output=type=registry
        push: true
        # List of output destinations (format: type=local,dest=path)

    - name: Build and push WorkerApp
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
      uses: docker/build-push-action@v2.3.0
      with:
        context: src/WorkerApp
        # List of tags
        tags: hallgeirl/kubedemo-worker:1.0
        # Push is a shorthand for --output=type=registry
        push: true
        # List of output destinations (format: type=local,dest=path)
